// Mobile/src/views/RegisterPage.vue
<template>
  <ion-page>
    <ion-content :fullscreen="true" class="register-content">
      <div class="bg-gradient">
        <div class="bg-shape bg-shape-1"></div>
        <div class="bg-shape bg-shape-2"></div>
        <div class="bg-shape bg-shape-3"></div>
      </div>

      <div class="register-wrapper">
        <!-- Brand -->
        <div class="brand-section">
          <div class="logo-container">
            <div class="logo-icon">
              <ion-icon :icon="constructOutline" />
            </div>
          </div>
          <h1 class="brand-title">Cloud S5</h1>
          <p class="brand-subtitle">Créez votre compte</p>
        </div>

        <!-- Card -->
        <div class="register-card">
          <h2 class="card-title">Inscription</h2>
          <p class="card-desc">Remplissez vos informations pour rejoindre la plateforme</p>

          <div class="form-group">
            <label class="form-label">Email</label>
            <div class="input-field" :class="{ focused: emailFocused }">
              <ion-icon :icon="mailOutline" class="field-icon" />
              <ion-input
                v-model="email"
                type="email"
                placeholder="votre@email.com"
                autocomplete="email"
                @ionFocus="emailFocused = true"
                @ionBlur="emailFocused = false"
              />
            </div>
          </div>

          <div class="form-group">
            <label class="form-label">Mot de passe</label>
            <div class="input-field" :class="{ focused: passwordFocused }">
              <ion-icon :icon="lockClosedOutline" class="field-icon" />
              <ion-input
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                placeholder="••••••••"
                autocomplete="new-password"
                @ionFocus="passwordFocused = true"
                @ionBlur="passwordFocused = false"
              />
              <button class="toggle-pw" @click="showPassword = !showPassword">
                <ion-icon :icon="showPassword ? eyeOffOutline : eyeOutline" />
              </button>
            </div>
          </div>

          <ion-button expand="block" class="register-btn" :disabled="loading" @click="onRegister">
            <ion-spinner v-if="loading" name="crescent" />
            <span v-else>Créer mon compte</span>
          </ion-button>

          <p class="help-text">
            Déjà un compte ? <router-link to="/login" class="link">Se connecter</router-link>
          </p>
        </div>

        <p class="footer-text">Cloud S5 © 2026 — Projet Madagascar</p>
      </div>

      <ion-alert
        :is-open="!!error"
        header="Erreur d'inscription"
        :message="error || ''"
        :buttons="['OK']"
        @didDismiss="error = null"
      />
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import {
  IonPage, IonContent, IonInput, IonButton, IonIcon, IonSpinner, IonAlert,
} from '@ionic/vue'
import {
  mailOutline, lockClosedOutline, constructOutline, eyeOutline, eyeOffOutline,
} from 'ionicons/icons'
import { useAuth } from '@/composables/useAuth'

const router = useRouter()
const { register } = useAuth()

const email = ref('')
const password = ref('')
const showPassword = ref(false)
const loading = ref(false)
const error = ref<string | null>(null)
const emailFocused = ref(false)
const passwordFocused = ref(false)

const onRegister = async () => {
  if (!email.value || !password.value) {
    error.value = 'Veuillez remplir tous les champs'
    return
  }
  error.value = null
  loading.value = true
  try {
    await register(email.value.trim(), password.value)
    await router.replace('/home')
  } catch (e) {
    error.value = e instanceof Error ? e.message : String(e)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.register-content {
  --background: #0f172a;
}

.bg-gradient {
  position: absolute; inset: 0; overflow: hidden; z-index: 0;
}

.bg-shape {
  position: absolute; border-radius: 50%; filter: blur(80px); opacity: 0.35;
}
.bg-shape-1 { width: 350px; height: 350px; background: #4f46e5; top: -80px; left: -60px; }
.bg-shape-2 { width: 280px; height: 280px; background: #0d9488; bottom: 10%; right: -60px; }
.bg-shape-3 { width: 200px; height: 200px; background: #6366f1; top: 45%; right: 30%; }

.register-wrapper {
  position: relative; z-index: 1;
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  min-height: 100%; padding: 24px 20px;
}

.brand-section { text-align: center; margin-bottom: 32px; }
.logo-container { margin-bottom: 16px; }
.logo-icon {
  width: 72px; height: 72px; margin: 0 auto;
  background: linear-gradient(135deg, #4f46e5, #6366f1);
  border-radius: 20px; display: flex; align-items: center; justify-content: center;
  font-size: 36px; color: white;
  box-shadow: 0 8px 32px rgba(79, 70, 229, 0.4);
}
.brand-title {
  font-size: 28px; font-weight: 800; color: #f8fafc; margin: 0 0 4px;
  letter-spacing: -0.02em;
}
.brand-subtitle { font-size: 14px; color: #94a3b8; margin: 0; }

.register-card {
  width: 100%; max-width: 400px;
  background: rgba(255, 255, 255, 0.97); backdrop-filter: blur(20px);
  padding: 32px 24px; border-radius: 20px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.card-title { font-size: 22px; font-weight: 700; color: #0f172a; margin: 0 0 4px; }
.card-desc { font-size: 14px; color: #64748b; margin: 0 0 28px; }

.form-group { margin-bottom: 20px; }
.form-label {
  display: block; font-size: 13px; font-weight: 600; color: #334155;
  margin-bottom: 8px; letter-spacing: 0.02em;
}

.input-field {
  display: flex; align-items: center; gap: 10px;
  background: #f1f5f9; border: 2px solid transparent; border-radius: 12px;
  padding: 0 16px; height: 52px; transition: all 0.25s ease;
}
.input-field.focused {
  background: #fff; border-color: #4f46e5;
  box-shadow: 0 0 0 4px rgba(79, 70, 229, 0.1);
}

.field-icon { font-size: 20px; color: #94a3b8; flex-shrink: 0; }
.input-field.focused .field-icon { color: #4f46e5; }

.input-field ion-input {
  --padding-start: 0; --padding-end: 0; --background: transparent;
  font-size: 15px; flex: 1; --color: #0f172a;
}

.toggle-pw {
  background: none; border: none; padding: 4px; cursor: pointer;
  color: #94a3b8; font-size: 20px; display: flex; align-items: center;
}

.register-btn {
  --background: #4f46e5; --background-hover: #4338ca;
  --border-radius: 12px; --padding-top: 16px; --padding-bottom: 16px;
  margin-top: 28px; font-weight: 700; font-size: 16px;
  --box-shadow: 0 4px 16px rgba(79, 70, 229, 0.3);
}

.help-text {
  text-align: center; font-size: 13px; color: #94a3b8; margin: 20px 0 0;
}
.link { color: #4f46e5; font-weight: 600; text-decoration: none; }

.footer-text {
  text-align: center; font-size: 12px; color: #475569; margin-top: 32px;
}
</style>

// Frontend/src/pages/RegisterPage.tsx
import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '@/auth/AuthContext'
import '../App.css'

export default function RegisterPage() {
  const { signup, loading } = useAuth()
  const nav = useNavigate()

  const [fullName, setFullName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const onSubmit = async (e: FormEvent) => {
    e.preventDefault()
    setError(null)
    try {
      await signup(email, password, fullName)
      nav('/', { replace: true })
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    }
  }

  return (
    <div className="app-shell" style={{ 
      background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px'
    }}>
      {/* Background Decor */}
      <div style={{
        position: 'absolute',
        top: '10%',
        right: '10%',
        width: '300px',
        height: '300px',
        background: 'radial-gradient(circle, rgba(59, 130, 246, 0.1) 0%, transparent 70%)',
        borderRadius: '50%',
        zIndex: 0
      }} />
      <div style={{
        position: 'absolute',
        bottom: '10%',
        left: '10%',
        width: '400px',
        height: '400px',
        background: 'radial-gradient(circle, rgba(59, 130, 246, 0.08) 0%, transparent 70%)',
        borderRadius: '50%',
        zIndex: 0
      }} />

      <div className="glass-card animate-fade-in" style={{
        width: '100%',
        maxWidth: '440px',
        padding: '40px',
        borderRadius: '24px',
        zIndex: 1,
        textAlign: 'center'
      }}>
        <div style={{
          width: '64px',
          height: '64px',
          background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
          borderRadius: '16px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          margin: '0 auto 24px',
          color: 'white',
          fontSize: '32px',
          boxShadow: '0 8px 16px rgba(59, 130, 246, 0.3)'
        }}>
          🗺️
        </div>

        <h1 style={{ fontSize: '28px', fontWeight: 800, color: '#0f172a', marginBottom: '8px', letterSpacing: '-0.5px' }}>
          Créer un compte
        </h1>
        <p style={{ color: '#64748b', marginBottom: '32px', fontSize: '15px' }}>
          Rejoignez la plateforme pour signaler des incidents
        </p>

        <form onSubmit={onSubmit} style={{ display: 'grid', gap: '20px', textAlign: 'left' }}>
          <div className="input-group">
            <span style={{ fontSize: '18px', color: '#94a3b8', marginRight: '8px' }}>👤</span>
            <input 
              value={fullName} 
              onChange={(e) => setFullName(e.target.value)} 
              placeholder="Nom complet" 
              required 
            />
          </div>

          <div className="input-group">
            <span style={{ fontSize: '18px', color: '#94a3b8', marginRight: '8px' }}>📧</span>
            <input 
              value={email} 
              onChange={(e) => setEmail(e.target.value)} 
              placeholder="Email professionnel" 
              type="email" 
              required 
            />
          </div>

          <div className="input-group">
            <span style={{ fontSize: '18px', color: '#94a3b8', marginRight: '8px' }}>🔒</span>
            <input 
              value={password} 
              onChange={(e) => setPassword(e.target.value)} 
              placeholder="Mot de passe (min 6)" 
              type={showPassword ? 'text' : 'password'} 
              minLength={6} 
              required 
            />
            <button 
              type="button"
              onClick={() => setShowPassword(!showPassword)}
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px', color: '#94a3b8', fontSize: '18px' }}
            >
              {showPassword ? '🙈' : '👁️'}
            </button>
          </div>

          <button className="btn-primary" disabled={loading} type="submit" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginTop: '12px' }}>
            {loading ? 'Création...' : (
              <>
                Créer mon compte
                <span style={{ fontSize: '18px' }}>→</span>
              </>
            )}
          </button>
        </form>

        {error && (
          <div style={{ 
            marginTop: '20px', 
            padding: '12px', 
            background: 'rgba(239, 68, 68, 0.1)', 
            color: '#ef4444', 
            borderRadius: '10px',
            fontSize: '14px'
          }}>
            {error}
          </div>
        )}

        <div style={{ marginTop: '32px', borderTop: '1px solid #f1f5f9', paddingTop: '24px', fontSize: '15px' }}>
          <p style={{ color: '#64748b' }}>
            Déjà un compte ? {' '}
            <Link to="/login" style={{ color: '#3b82f6', textDecoration: 'none', fontWeight: 600 }}>
              Se connecter
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
